### ISSUE TITLE
API Failure

### ISSUE THREAD

**Issue by blaqqendwhyt** [FAXES/DiscordWhitelist#10]
Hellow,

i set it right, and it work 80% of the times,

and the 20% :
[script:DiscordWhitel] There was an issue with the Discord API request. Is the guild ID & bot token correct?

I don't understand why...

**Comment by Rosavix** [comment]
Same issue

**Comment by nilPadisha** [comment]
It looks like this only occurs when the player isn't in the discord server.

**Comment by blaqqendwhyt** [comment]
but he is in the discord :p

**Comment by odessadraekavik** [comment]
Same issue here, it's been happening from time to time since 2 days ago... we have to manually stop the discord whitelist resource everytime so our players can connect, this is frustrating :x

**Comment by FAXES** [comment]
> It looks like this only occurs when the player isn't in the discord server.

Yeah, that also appears from my looks into it.

**Comment by FAXES** [comment]
> Same issue here, it's been happening from time to time since 2 days ago... we have to manually stop the discord whitelist resource everytime so our players can connect, this is frustrating :x

How popular is your server? Or how many connection (attempts) would you say you average per day?

**Comment by nilPadisha** [comment]
> > It looks like this only occurs when the player isn't in the discord server.
> 
> Yeah, that also appears from my looks into it.

My hunch says it's failing to handle the error/failed request

> but he is in the discord :p

That doesn't need to be the main issue, there can be issues while FiveM tries to communicate with the Discord Application. Some examples I can think of is that they use Discord Web, maybe BetterDiscord can cause issues or it could be possible that you need to link discord with fivem when it detects it at the beginning.
