### ISSUE TITLE
Occasional Connection Failed > Failed handshake

### ISSUE THREAD

**Issue by 1mRAAAH** [FAXES/DiscordWhitelist#14]
Using DiscordWhiteList in a legit, clean and new server. pepe-core. 
Pretty often we get an issue with the script where it says (while loading) that it's still checking the ID and eventually 
closes on the user with the message 
"Failed handshake to server <ip> - transfer closed with outstanding read data reamaining - CURL error code 18 (Transferred a partial file).

What to do about this issue. need to stop the script and reload it. While the script is stopped, everyone that wants can join and won't be removed when not in the discord.

**Comment by ByRambo18** [comment]
Hello, the same thing happens to me, and it is very annoying because I have a large audience, it is too annoying that many users because of the script that is necessary on my server, many can not connect and we lose users because of the problem, the same error happens to me.

**Comment by FAXES** [comment]
New version releasing :)
