### ISSUE TITLE
SCRIPT ERROR when someone tries to join that isnt on our discord server

### ISSUE THREAD

**Issue by Xentran94** [FAXES/DiscordWhitelist#15]
If someone tries to join our fivem server that is not on our discord server we get this error in our server-console: 

```
[script:DiscordWhitel] SCRIPT ERROR in event `playerConnecting': TypeError: Cannot read property 'indexOf' of null
[script:DiscordWhitel] > getUserDiscord (@DiscordWhitelist/server.js:50)
[script:DiscordWhitel] > <unknown> (@DiscordWhitelist/server.js:57)
```

the player who tries to connect gets a timeout message without any info to join our discord.

Please help

**Comment by FAXES** [comment]
New version releasing :)
