### ISSUE TITLE
Guild Error while connecting

### ISSUE THREAD

**Issue by eXahostCOM** [FAXES/DiscordWhitelist#18]
Hey, tonight all of a sudden every player got the following error when connecting.... However, changes were made neither to the Discord server, nor to the resource

Player Error Message: Guild not detected. It seems you're not in the guild for this community

Server Error Message: [script:DiscordWhitel] PLAYERNAME is not in the guild.

Thanks for help :)

**Comment by FAXES** [comment]
New version releasing :)
