### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by ByRambo18** [FAXES/DiscordWhitelist#20]
![image](https://user-images.githubusercontent.com/78485161/147364381-d5edf5f3-94ef-47a6-a2d8-a3f8c94ba67a.png)

**Comment by Kelom78** [comment]
same issue, it appeared after the server had been up with no issues in 2 hours

**Comment by DylanMulti** [comment]
Yeah I get this error as well.

**Comment by FAXES** [comment]
Duplicate:
https://github.com/FAXES/DiscordWhitelist/issues/22
