### ISSUE TITLE
Errors, players with right roles cant connect.

### ISSUE THREAD

**Issue by kFxDaKing** [FAXES/DiscordWhitelist#22]
**Error:**
`[script:DiscordWhitel] Error: {"message":"Request failed with status code 404","name":"Error","stack":"Error: Request failed with status code 404\n    at createError (C:\\Users\\admin\\Desktop\\MNRP\\resources\\[DISCORD]\\DiscordWhitelist\\node_modules\\axios\\lib\\core\\createError.js:16:15)\n    at settle (C:\\Users\\admin\\Desktop\\MNRP\\resources\\[DISCORD]\\DiscordWhitelist\\node_modules\\axios\\lib\\core\\settle.js:17:12)\n    at IncomingMessage.handleStreamEnd (C:\\Users\\admin\\Desktop\\MNRP\\resources\\[DISCORD]\\DiscordWhitelist\\node_modules\\axios\\lib\\adapters\\http.js:269:11)\n    at IncomingMessage.emit (node:events:406:35)\n    at endReadableNT (node:internal/streams/readable:1343:12)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)","config":{"url":"https://discord.com/api/v9/guilds/734134817632813096/members/830025348032364554","method":"get","headers":{"Content-Type":"application/json","Authorization":"Bot XXXXXXXXXXXXTOKEN","User-Agent":"axios/0.21.4"},"baseURL":"https://discord.com/api/v9","transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false}}}
[script:DiscordWhitel] [4.0] Cody McMiller is not in the guild.
[script:DiscordWhitel] SCRIPT ERROR in promise (unhandled): TypeError: Cannot read properties of undefined (reading 'data')
[script:DiscordWhitel] > <unknown> (@DiscordWhitelist/server.js:140)
[script:DiscordWhitel] > processTicksAndRejections (node:internal/process/task_queues:96)`

Some players cannot connect (like 70%) , if they have one of the roles.

**We keep getting this:**
`FillOS is not whitelisted. Cache created
[script:DiscordWhitel] [4.0] FillOSs Roles:  [
[script:DiscordWhitel]   "734134817632813103"
[script:DiscordWhitel] ]`
Or just
`"name" is not whitelisted.` (but he have the role)

**And here is our config:**

![image](https://user-images.githubusercontent.com/52855882/149941619-c375ea5e-ad2b-4714-9fef-eb84c1ca17d8.png)

**Comment by DylanMulti** [comment]
I have exactly the same issue, then you have to stop the script for a couple of minutes and start it again to work

**Comment by k2xp** [comment]
i got the same issue to but if you only make 1 role whitelisted theres no problems at all...

**Comment by ghost** [comment]
I have the same problem and I only have one whitelisted role and I have to restart the script when I give someone the role so they can login.

**Comment by oevertje003** [comment]
yep, i have the same issue. Anyone has a solution?

**Comment by soniXx123** [comment]
same issue. Looking for an alternative script.

**Comment by FAXES** [comment]
If you're on the newly released version this should be fixed. However, report back any issues

**Comment by DylanMulti** [comment]
Thanks @FAXES Appreciate the update!

**Comment by FAXES** [comment]
Fixed in release 4.1

https://github.com/FAXES/DiscordWhitelist/releases/tag/4.1
