### ISSUE TITLE
Connectionproblem for some users

### ISSUE THREAD

**Issue by FenKeN** [FAXES/DiscordWhitelist#23]
Hello, i just have isntalled the DiscordWhitelist bot, and it works fine for the most of people. Im the Serverowner and i and some other ones getting this error in the console:

[script:DiscordWhitel] SCRIPT ERROR in event `playerConnecting': TypeError: Cannot read properties of null (reading 'indexOf')
[script:DiscordWhitel] > getUserDiscord (@DiscordWhitelist/server.js:34)
[script:DiscordWhitel] > <unknown> (@DiscordWhitelist/server.js:41)
[script:DiscordWhitel]

Screenshot from a user: https://cdn.discordapp.com/attachments/800940362482057286/940277760889348137/unknown.png

**Comment by FAXES** [comment]
Update to the 4.0 release
