### ISSUE TITLE
Refresh Discord Roles

### ISSUE THREAD

**Issue by YxngRxkker** [FAXES/DiscordWhitelist#24]
Does somebody know where i can change the refresh time. When i put a whitelist role in discord and connect to fivem it doesn't work instantly. There is probably some refresh time right? Anybody here that knows the answer?

**Comment by FAXES** [comment]
Should be instant. However, there is a custom cache system built-in in which you can change your server.js file near the top.

Take note that changing this may cause API rate limit issues, I recommend nothing lower than 5m
