### ISSUE TITLE
error connexion

### ISSUE THREAD

**Issue by Brooksiito** [FAXES/DiscordWhitelist#26]
![Capture](https://user-images.githubusercontent.com/78375212/155878983-17ecd145-8853-445a-9046-14ebbc0ec824.PNG)

**Comment by Brooksiito** [comment]
@FAXES the discordwhitelist got this error many times in a day, and crash when we are more than 60/70 players on serv

**Comment by FAXES** [comment]
Fixed in release 4.1

https://github.com/FAXES/DiscordWhitelist/releases/tag/4.1
