### ISSUE TITLE
error connexion

### ISSUE THREAD

**Issue by Brooksiito** [FAXES/DiscordWhitelist#27]
Yo,
I have an issue with whitelist discord.
When we passed 70 players, someone got error msg that say they arent allowlist but they got the role.
When an influx of player, discord whitelist like crashing whitout error in console...
Did you have a solution ?

**Comment by FAXES** [comment]
Are you on version 4.1?
Also, consider changing the cacheTime value in the config area of the `server.js`. This cache time is to save us from Discord rate limits, so if a user tries joining without the role then gets it, they'd have to wait the configured amount of cache hours to have it get the updated information from Discord.

**Comment by Brooksiito** [comment]
yes i am.
Ok will try this

**Comment by Brooksiito** [comment]
![image](https://user-images.githubusercontent.com/78375212/156390290-ef734aec-8f7b-4918-929b-fe3c811107d8.png)
@FAXES my cachtime is 2h

**Comment by FAXES** [comment]
Super odd seeming I can't recreate this at all.

Try regenerating your Discord bot token and throw that one in
