### ISSUE TITLE
Unable to join a server although I have allowlist role.

### ISSUE THREAD

**Issue by LielR** [FAXES/DiscordWhitelist#28]
I have the role which I configured as allowlisted and still I can't join the server.
It works only after restarting the script...

**Comment by kevintransp** [comment]
Is this the same error i have?
Connection stays at your discord id is being checked with our alowlist

**Comment by Brooksiito** [comment]
same error when we have 60/70 players in and 10 players try to connect in same time

**Comment by FAXES** [comment]
@L1R26 You can configure the cacheMaxTime in the `server.js`

@kevintransp What version are you on?

@Brooksiito Going from your other open issue, you can turn on debug mode to show more console outputs.
