### ISSUE TITLE
Player not getting Cached

### ISSUE THREAD

**Issue by RealKnoblauchbrot** [FAXES/DiscordWhitelist#33]
Some Players when they join, don't get cached.
I have enabled debug mode to see what the problem is.
But for some reason it says nothing(not getting cached)
![grafik](https://user-images.githubusercontent.com/60825241/162317639-50912550-b819-4dca-a7d4-384858f881ff.png)

But after Server Restart it works again:
![grafik](https://user-images.githubusercontent.com/60825241/162318096-ac3adf67-8f9f-4828-b56a-03452bb55883.png)

I have the newest version of DiscordWhitelist installed.

**Comment by FAXES** [comment]
Seems odd, like it's not even executing in the first screenshot. @TheRealCasiv2 Can you test to see if it conflicts by turning off they `connectqueue` resource you have?

**Comment by RealKnoblauchbrot** [comment]
I have been testing it with and without connectqueue and for some reason it works now even with connectqueue, If i get it again ill open a new Issue

**Comment by FAXES** [comment]
Perfect, resources are odd, even starting them in opposite order may help.
