### ISSUE TITLE
[Solved] Change "whitelist" to "allowlist"

### ISSUE THREAD

**Issue by Bulle93230** [FAXES/DiscordWhitelist#34]
Hi can i ask you why on **var notWhitelistedMessage** i put the word "Whitelist" it automatically change it to "Allowlist" please ?
And how to remove that please

Thank you (and nice script <3)

**Comment by FAXES** [comment]
Hey, I hope you're having a great day

This is a FiveM restriction that they have on their platform. There's nothing that can be changed to resolve this sadly.

**Comment by Bulle93230** [comment]
Oh thank you

**Comment by Esterze** [comment]
Umm, just make it white-list or use special symbols.
