### ISSUE TITLE
You're not allowlisted.

### ISSUE THREAD

**Issue by sxphamari** [FAXES/DiscordWhitelist#35]
Getting that prompt even tho I don't set that kind of message. My solution for that is to restart script for them can go in the city.

**Comment by prosilentgamer2** [comment]
so if you have a solution why open an issue?

**Comment by pjguzman** [comment]
make sure that on txadmin Whitelist id disabled

**Comment by Psych0Tech** [comment]
Disable TXadmin Whitelist

**Comment by FAXES** [comment]
https://discord.gg/faxes has a channel in it that totally goes through this issue.
