### ISSUE TITLE
userHasRole not working

### ISSUE THREAD

**Issue by zf-development** [FAXES/DiscordWhitelist#36]
exports('userHasRole', (src, roles) => {
    if(!work) return;
    return new Promise((res, rej) => {
        getUserDiscord(src, function(userId) {
            if(userId) {
                axios(`/guilds/${guildId}/members/${userId}`).then((resDis) => {
                    if(!resDis.data) {
                        res(false)
                    }
                    const hasRole = resDis.data.roles.some((cRole, i) => resDis.data.roles.includes(roles[i]));
                    if(hasRole) {
                        res(true)
                    } else {
                        res(false)
                    }
                    
                }).catch((err) => {
                    res(false)
                });
            } else {
                res(false)
            }
        });
    });
});

I don't know why but it's not working...
When printing resDis.data it doesn't shows anything.

I'm using this to call the exports exports['DiscordWhitelist']:userHasRole(src, role)
[ src ] = source
[ role ] = id of the role in a string like "1011371533727444992"

**Comment by FAXES** [comment]
Try pass the role Id in an array
