### ISSUE TITLE
The need to restart the server in order to register a player as whitelisted

### ISSUE THREAD

**Issue by Esterze** [FAXES/DiscordWhitelist#38]
Giving the Whitelist role is not enough, the server - or rather the script won't register it.
So I need to restart the server in order for the script to register any changes.

Did I make a mistake or is the script outdated, thus broken?

**Comment by Esterze** [comment]
Oh yes, last release on 28 February, I wonder what could go wrong, gosh, it's been 8 months, it's really no wonder.

**Comment by alexius544** [comment]
It’s probably outdated in that manner. Although I don’t believe that should be happening. Have you tried re-installing? I’d recommend checking some other scripts out if you haven’t already…

**Comment by Esterze** [comment]
Reinstalling, why? I didn't change the code.

**Comment by c0deina** [comment]
This is a bug but it is how it is intended to work, if you want to have instant re-checks comment line https://github.com/FAXES/DiscordWhitelist/blob/master/server.js#L165

That will not store cache and will force refreshing when they fail to be whitelisted.

**Comment by FAXES** [comment]
> Giving the Whitelist role is not enough, the server - or rather the script won't register it.
> So I need to restart the server in order for the script to register any changes.

It works from a cache to reduce the amounts of requests the server makes to Discord to eliminate rate limits. This is the design. You just need to double-check the configuration of how you want your resources.



> Oh yes, last release on 28 February, I wonder what could go wrong, gosh, it's been 8 months, it's really no wonder.

Time means nothing, many FiveM resources from 2017 still work.
