### ISSUE TITLE
[4.0] Guild ID is incorrect or bot isn't in guild. Stopping...

### ISSUE THREAD

**Issue by DerDemolierer** [FAXES/DiscordWhitelist#41]
cfx> [script:DiscordWhitel] [4.0] Guild ID is incorrect or bot isn't in guild. Stopping...

How to solve this ? I have correctly set my Guild ID

**Comment by FAXES** [comment]
This will only throw if the guild can't be found by the bot. This is caused by either of these two.

- Bot isn't within the set guild.
- Guild ID in the config is incorrect.
