### ISSUE TITLE
CURL Errorcode 18

### ISSUE THREAD

**Issue by ElecTwix** [FAXES/DiscordWhitelist#7]
ıdk why but some thing worng with script. I add role ids. but I am getting CURL Errorcode 18 ıdk doesn't any don't whitelist message at all , I remove all my resoruce when I test this only 2. Can you help me I am in your discord thanks.

**Comment by FAXES** [comment]
Update your FX server

**Comment by BauerButBauerDied** [comment]
I'm having this issue as well, just updated my FX Server, so that isn't the issue, at least for me.

**Comment by BauerButBauerDied** [comment]
> I'm having this issue as well, just updated my FX Server, so that isn't the issue, at least for me.

Turns out I did not install the discordroles resource correctly. Whoops!

(forgot to run npm install)
