### ISSUE TITLE
SCRIPT ERROR in timer: Error: No such export isRolePresent in resource discordroles

### ISSUE THREAD

**Issue by ShiftyGaming** [FAXES/DiscordWhitelist#8]
I recently switched from my Local resource folder to Linux, but I keep getting this error while trying to join.

```
SCRIPT ERROR in timer: Error: No such export isRolePresent in resource discordroles

>  (@discordwhitelist/server.js:39)
```

**Comment by miguelcollaco** [comment]
same issue

**Comment by 0ssg** [comment]
same issue

**Comment by OGMatrix** [comment]
same issue

**Comment by KingCora** [comment]
For some reason the installation guide on the website is talking about DiscordRoles version 3.0, the only available download is version 2.3 on github and fivem only has 2.3 as well, maybe this is a mistake by the Developer? 

Anyway to fix your problem you need to download the resource called discordroles I have provided a link below to the download and installation instruction for DiscordWhiteList and DiscordRoles (the dependency)

https://github.com/sadboilogan/discordroles
https://docs.faxes.zone/docs/discord-whitelist-setup-old/

**Comment by Baelroak** [comment]
> I recently switched from my Local resource folder to Linux, but I keep getting this error while trying to join.
> 
> ```
> SCRIPT ERROR in timer: Error: No such export isRolePresent in resource discordroles
> 
> >  (@discordwhitelist/server.js:39)
> ```



> same issue


For some reason the documentation leads you to believe you have downloaded version 3.0 of DiscordWhitelist which requires badage-discord-api, this is not the case, the only available download on github and FiveM is version 2.3, this version requires a resource called DiscordRoles as a dependency, I have provided a link the resource and proper installation instructions for DiscordWhiteList and DIscordRoles below.

https://docs.faxes.zone/docs/discord-whitelist-setup-old/
https://github.com/sadboilogan/discordroles

This should fix both of your problems.

**Comment by FAXES** [comment]
Now resolved fully as it can't be a possible error.
